import type { DeveloperTool } from "@/lib/developer-tools/types";

export const developerTools: DeveloperTool[] = [
  {
    id: "blink-api",
    slug: "blink-api",
    name: "Blink",
    description:
      "Bitcoin Lightning banking APIs for wallets, remittances, and payment apps.",
    overview:
      "Blink (by Galoy) exposes GraphQL APIs for Lightning and on-chain Bitcoin balances, invoices, and account flows — useful when you want production-ready Lightning rails without running your own node stack from day one.",
    whyUse: [
      "Ship Lightning features faster with a hosted API surface.",
      "Clear GraphQL schema for balances, invoices, and payments.",
      "Good fit for wallet and remittance prototypes on Pull projects.",
    ],
    buildUseCase: "Payment Apps",
    category: "APIs",
    tags: ["Lightning", "GraphQL", "Payments", "API"],
    openSource: false,
    difficulty: "Intermediate",
    website: "https://www.blink.sv",
    docs: "https://dev.blink.sv",
    github: "https://github.com/GaloyMoney",
    logo: "BL",
    featured: true,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
      { title: "Bitcoin roadmap", href: "/roadmaps/bitcoin" },
    ],
    projectIdeas: [
      {
        title: "Lightning Wallet",
        description: "Send tips over Lightning using invoices from the Blink API.",
        href: "/projects",
      },
      {
        title: "Merchant Checkout",
        description: "Accept Lightning payments for a small merchant checkout.",
        href: "/projects",
      },
    ],
    tutorials: [
      { title: "Blink developer docs", href: "https://dev.blink.sv" },
    ],
  },
  {
    id: "lightspark",
    slug: "lightspark",
    name: "Lightspark",
    description:
      "Enterprise Lightning infrastructure and APIs for global Bitcoin payments.",
    overview:
      "Lightspark provides Lightning network infrastructure and developer APIs aimed at companies that need reliable, scalable Lightning connectivity without operating every node themselves.",
    whyUse: [
      "Enterprise-oriented Lightning infrastructure.",
      "APIs designed for payment products at scale.",
      "Useful when exploring production Lightning architecture.",
    ],
    buildUseCase: "Payment Apps",
    category: "APIs",
    tags: ["Lightning", "API", "Payments", "Enterprise"],
    openSource: false,
    difficulty: "Advanced",
    website: "https://www.lightspark.com",
    docs: "https://docs.lightspark.com",
    logo: "LS",
    featured: true,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
    ],
    projectIdeas: [
      {
        title: "Merchant Checkout",
        description: "Prototype Lightning checkout with Lightspark APIs.",
      },
    ],
  },
  {
    id: "breez-sdk",
    slug: "breez-sdk",
    name: "Breez",
    description:
      "Embed non-custodial Lightning into apps with a multi-platform SDK.",
    overview:
      "The Breez SDK helps developers add Lightning payments to mobile and desktop apps, abstracting node connectivity and common wallet flows so you can focus on product UX.",
    whyUse: [
      "Non-custodial Lightning embedding for apps.",
      "Cross-platform SDK surface for product builders.",
      "Strong fit for wallet and tipping experiments.",
    ],
    buildUseCase: "Lightning Wallets",
    category: "SDKs",
    tags: ["Lightning", "SDK", "Mobile", "Non-custodial"],
    openSource: true,
    difficulty: "Intermediate",
    website: "https://breez.technology",
    docs: "https://sdk-doc-spark.breez.technology",
    github: "https://github.com/breez",
    logo: "BZ",
    featured: true,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
    ],
    projectIdeas: [
      {
        title: "Lightning Wallet",
        description: "Build in-app tipping with the Breez SDK.",
        href: "/projects",
      },
      {
        title: "Self Custody Tool",
        description: "Prototype a Lightning-enabled mobile wallet experience.",
        href: "/projects",
      },
    ],
  },
  {
    id: "ldk",
    slug: "ldk",
    name: "LDK",
    description:
      "Lightning Dev Kit — modular libraries for self-custodial Lightning apps.",
    overview:
      "LDK (Lightning Dev Kit) provides flexible Lightning protocol libraries and higher-level node packages so developers can embed self-custodial Lightning without running a full node stack from scratch.",
    whyUse: [
      "Modular Lightning building blocks in Rust with bindings.",
      "Path to self-custodial wallets and mobile Lightning apps.",
      "Strong open-source contribution surface.",
    ],
    buildUseCase: "Lightning Wallets",
    category: "SDKs",
    tags: ["Lightning", "Rust", "SDK", "Non-custodial"],
    openSource: true,
    difficulty: "Advanced",
    website: "https://lightningdevkit.org",
    docs: "https://lightningdevkit.org",
    github: "https://github.com/lightningdevkit/rust-lightning",
    logo: "LD",
    featured: true,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
    ],
    projectIdeas: [
      {
        title: "Lightning Wallet",
        description: "Embed a self-custodial Lightning node with LDK Node.",
        href: "/projects",
      },
    ],
    tutorials: [
      {
        title: "LDK Node docs",
        href: "https://docs.rs/ldk-node/latest/ldk_node/",
      },
    ],
  },
  {
    id: "bitcoinjs-lib",
    slug: "bitcoinjs-lib",
    name: "bitcoinjs-lib",
    description:
      "JavaScript/TypeScript library for Bitcoin transactions, addresses, and PSBTs.",
    overview:
      "bitcoinjs-lib is a widely used Bitcoin library for Node.js and browsers. It covers transactions, scripts, addresses, and PSBT flows for web and TypeScript wallet tooling.",
    whyUse: [
      "Standard JS/TS toolkit for Bitcoin app builders.",
      "Strong fit for browser and Node wallet prototypes.",
      "Well-documented transaction and PSBT helpers.",
    ],
    buildUseCase: "Self-Custody Wallets",
    category: "SDKs",
    tags: ["Bitcoin", "JavaScript", "TypeScript", "SDK"],
    openSource: true,
    difficulty: "Intermediate",
    website: "https://github.com/bitcoinjs/bitcoinjs-lib",
    docs: "https://bitcoinjs.github.io/bitcoinjs-lib/",
    github: "https://github.com/bitcoinjs/bitcoinjs-lib",
    logo: "BJ",
    featured: true,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Bitcoin roadmap", href: "/roadmaps/bitcoin" },
    ],
    projectIdeas: [
      {
        title: "Self Custody Tool",
        description: "Build address and PSBT flows with bitcoinjs-lib.",
        href: "/projects",
      },
    ],
  },
  {
    id: "nostr-tools",
    slug: "nostr-tools",
    name: "nostr-tools",
    description:
      "Low-level TypeScript toolkit for Nostr clients, relays, and events.",
    overview:
      "nostr-tools provides primitives for Nostr keys, events, filters, and relay communication — a common foundation for building clients and Lightning-zap enabled social apps.",
    whyUse: [
      "Core building blocks for Nostr clients.",
      "TypeScript-friendly and widely adopted.",
      "Pairs well with Lightning tip and zap experiments.",
    ],
    buildUseCase: "Nostr Clients",
    category: "SDKs",
    tags: ["Nostr", "TypeScript", "SDK", "Clients"],
    openSource: true,
    difficulty: "Intermediate",
    website: "https://github.com/nbd-wtf/nostr-tools",
    docs: "https://jsr.io/@nostr/tools",
    github: "https://github.com/nbd-wtf/nostr-tools",
    logo: "NT",
    featured: false,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Bitcoin roadmap", href: "/roadmaps/bitcoin" },
    ],
    projectIdeas: [
      {
        title: "Nostr Client",
        description: "Publish and fetch notes with nostr-tools.",
        href: "/projects",
      },
    ],
  },
  {
    id: "voltage",
    slug: "voltage",
    name: "Voltage",
    description:
      "Managed Lightning and Bitcoin node infrastructure for builders.",
    overview:
      "Voltage provides hosted Lightning and Bitcoin infrastructure so teams can spin up nodes and services without running hardware ops from scratch.",
    whyUse: [
      "Fast path to a Lightning node for prototypes.",
      "Infrastructure focus for apps that need node access.",
      "Pairs well with API and SDK experiments.",
    ],
    buildUseCase: "Bitcoin Infrastructure",
    category: "Infrastructure",
    tags: ["Lightning", "Nodes", "Infrastructure", "Hosting"],
    openSource: false,
    difficulty: "Intermediate",
    website: "https://voltage.cloud",
    docs: "https://docs.voltage.cloud",
    logo: "VO",
    featured: true,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
    ],
    projectIdeas: [
      {
        title: "Lightning Wallet",
        description: "Back a tipping product with a managed Lightning node.",
      },
    ],
  },
  {
    id: "alby",
    slug: "alby",
    name: "Alby",
    description:
      "Browser extension wallet and Lightning tools for the web.",
    overview:
      "Alby brings Lightning to the browser with an extension wallet, Nostr support, and APIs that help web apps request payments and identity-related flows.",
    whyUse: [
      "Lightning UX for web apps and content tipping.",
      "Familiar extension-wallet mental model for users.",
      "Useful for Nostr + Lightning experiments.",
    ],
    buildUseCase: "Lightning Wallets",
    category: "Wallets",
    tags: ["Lightning", "Browser", "Nostr", "Wallet"],
    openSource: true,
    difficulty: "Beginner",
    website: "https://getalby.com",
    docs: "https://guides.getalby.com",
    github: "https://github.com/getAlby",
    logo: "AL",
    featured: false,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
    ],
    projectIdeas: [
      {
        title: "Lightning Wallet",
        description: "Add web tipping with Alby’s browser wallet flows.",
        href: "/projects",
      },
      {
        title: "Nostr Client",
        description: "Combine Nostr identity with Lightning zaps.",
        href: "/projects",
      },
    ],
  },
  {
    id: "fedimint",
    slug: "fedimint",
    name: "Fedimint",
    description:
      "Federated mint protocol for community Bitcoin custody and e-cash.",
    overview:
      "Fedimint enables communities to custody Bitcoin collaboratively through federated mints, exposing modules for peg-ins, e-cash notes, and Lightning gateways.",
    whyUse: [
      "Explore community custody beyond single-sig wallets.",
      "Open protocol with active Rust contributors.",
      "Strong research + contribution surface on Pull.",
    ],
    buildUseCase: "Self-Custody Wallets",
    category: "SDKs",
    tags: ["Bitcoin", "Federation", "Privacy", "SDK", "Wasm"],
    openSource: true,
    difficulty: "Advanced",
    website: "https://fedimint.org",
    docs: "https://sdk.fedimint.org",
    github: "https://github.com/fedimint/fedimint",
    logo: "FM",
    featured: true,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Bitcoin roadmap", href: "/roadmaps/bitcoin" },
      { title: "Fedimint organization", href: "/organizations/fedimint" },
    ],
    projectIdeas: [
      {
        title: "Self Custody Tool",
        description: "Build ecash into an app with the Fedimint SDK.",
      },
    ],
  },
  {
    id: "cashu",
    slug: "cashu",
    name: "Cashu",
    description:
      "Chaumian e-cash protocol for Bitcoin Lightning mints.",
    overview:
      "Cashu is a free and open-source Chaumian ecash system for Bitcoin. Mints issue blinded tokens that users can hold and transfer with strong privacy properties.",
    whyUse: [
      "Learn Chaumian e-cash on Lightning rails.",
      "Growing mint and wallet ecosystem.",
      "Great for privacy-focused experiments.",
    ],
    buildUseCase: "Payment Apps",
    category: "SDKs",
    tags: ["Lightning", "E-cash", "Privacy", "SDK"],
    openSource: true,
    difficulty: "Intermediate",
    website: "https://cashu.space",
    docs: "https://docs.cashu.space",
    github: "https://github.com/cashubtc",
    logo: "CU",
    featured: false,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
    ],
    projectIdeas: [
      {
        title: "Bitcoin Payment App",
        description: "Prototype private tips using Cashu SDKs and mints.",
      },
    ],
  },
  {
    id: "lnbits",
    slug: "lnbits",
    name: "LNbits",
    description:
      "Extensible Lightning accounts system with apps and APIs.",
    overview:
      "LNbits sits on top of Lightning funding sources and provides multi-account wallets, extensions, and APIs — popular for experiments, faucets, and small Lightning products.",
    whyUse: [
      "Rapid Lightning app scaffolding.",
      "Extension ecosystem for demos and tools.",
      "Friendly beginner-to-intermediate on-ramp.",
    ],
    buildUseCase: "Payment Apps",
    category: "Open Source",
    tags: ["Lightning", "API", "Extensions", "Python"],
    openSource: true,
    difficulty: "Beginner",
    website: "https://lnbits.com",
    docs: "https://docs.lnbits.com",
    github: "https://github.com/lnbits/lnbits",
    logo: "LN",
    featured: false,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
    ],
    projectIdeas: [
      {
        title: "Lightning Wallet",
        description: "Stand up tipping or faucet flows with LNbits.",
        href: "/projects",
      },
      {
        title: "Merchant Checkout",
        description: "Use LNbits extensions for simple merchant demos.",
        href: "/projects",
      },
    ],
  },
  {
    id: "btcpayserver",
    slug: "btcpayserver",
    name: "BTCPay Server",
    description:
      "Self-hosted Bitcoin payment processor for merchants and communities.",
    overview:
      "BTCPay Server is a free, open-source, self-hosted payment processor. Accept Bitcoin and Lightning without fees or intermediaries, with plugins and a strong contributor community.",
    whyUse: [
      "Self-sovereign merchant payments.",
      "Deep open-source contribution opportunities.",
      "Ideal Pull Build → Contribute bridge.",
    ],
    buildUseCase: "Merchant Checkout",
    category: "Open Source",
    tags: ["Bitcoin", "Lightning", "Merchants", "Self-hosted"],
    openSource: true,
    difficulty: "Intermediate",
    website: "https://btcpayserver.org",
    docs: "https://docs.btcpayserver.org",
    github: "https://github.com/btcpayserver/btcpayserver",
    logo: "BP",
    featured: true,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Bitcoin roadmap", href: "/roadmaps/bitcoin" },
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
    ],
    projectIdeas: [
      {
        title: "Merchant Checkout",
        description: "Deploy BTCPay and integrate a checkout flow.",
        href: "/projects",
      },
    ],
  },
  {
    id: "strike-api",
    slug: "strike-api",
    name: "Strike",
    description:
      "Bitcoin and Lightning APIs for payments, payouts, and currency conversion.",
    overview:
      "Strike exposes developer APIs for sending and receiving Bitcoin and Lightning payments, bridging cash balances and Bitcoin rails so apps can move value without operating a node.",
    whyUse: [
      "Single integration for on-chain and Lightning flows.",
      "Strong fit for remittance and payment products.",
      "Clear developer docs for production integrations.",
    ],
    buildUseCase: "Payment Apps",
    category: "APIs",
    tags: ["Lightning", "Bitcoin", "Payments", "API"],
    openSource: false,
    difficulty: "Intermediate",
    website: "https://strike.me",
    docs: "https://docs.strike.me",
    logo: "ST",
    featured: true,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
      { title: "Bitcoin roadmap", href: "/roadmaps/bitcoin" },
    ],
    projectIdeas: [
      {
        title: "Bitcoin Payment App",
        description: "Send and receive Lightning payments with the Strike API.",
        href: "/projects",
      },
      {
        title: "Merchant Checkout",
        description: "Accept Bitcoin checkout powered by Strike.",
        href: "/projects",
      },
    ],
    tutorials: [
      { title: "Strike developer portal", href: "https://developer.strike.me" },
    ],
  },
  {
    id: "opennode",
    slug: "opennode",
    name: "OpenNode",
    description:
      "Bitcoin and Lightning payment processing APIs for merchants and apps.",
    overview:
      "OpenNode provides REST APIs for creating charges, payouts, and Lightning or on-chain settlement — a common path for merchant checkout and remittance prototypes.",
    whyUse: [
      "Simple charge and payout API surface.",
      "Lightning and on-chain payment support.",
      "Useful for merchant and ecommerce experiments.",
    ],
    buildUseCase: "Merchant Checkout",
    category: "APIs",
    tags: ["Lightning", "Bitcoin", "Merchants", "API"],
    openSource: false,
    difficulty: "Beginner",
    website: "https://www.opennode.com",
    docs: "https://developers.opennode.com",
    github: "https://github.com/opennodedev",
    logo: "ON",
    featured: false,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
    ],
    projectIdeas: [
      {
        title: "Merchant Checkout",
        description: "Create Lightning charges and track settlement with OpenNode.",
        href: "/projects",
      },
    ],
  },
  {
    id: "amboss",
    slug: "amboss",
    name: "Amboss",
    description:
      "GraphQL APIs for Lightning payments, liquidity, and network intelligence.",
    overview:
      "Amboss offers GraphQL APIs across payments and Lightning tooling — useful for builders who need payment flows plus network data and liquidity surfaces.",
    whyUse: [
      "GraphQL endpoints for payments and Lightning products.",
      "TypeScript SDK for faster integration.",
      "Sandbox-oriented path for Lightning experiments.",
    ],
    buildUseCase: "Payment Apps",
    category: "APIs",
    tags: ["Lightning", "GraphQL", "Payments", "API"],
    openSource: false,
    difficulty: "Intermediate",
    website: "https://amboss.space",
    docs: "https://docs.amboss.tech/developer",
    logo: "AM",
    featured: false,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
    ],
    projectIdeas: [
      {
        title: "Bitcoin Payment App",
        description: "Send and receive Lightning payments via Amboss APIs.",
        href: "/projects",
      },
    ],
  },
  {
    id: "esplora",
    slug: "esplora",
    name: "Esplora",
    description:
      "Open-source Blockstream HTTP API for Bitcoin chain data and transactions.",
    overview:
      "Esplora is Blockstream’s open-source explorer stack with a clean HTTP API for addresses, transactions, blocks, and fee-related chain data — often used behind wallet and indexer UX.",
    whyUse: [
      "Battle-tested open-source Bitcoin data API.",
      "Self-hostable explorer backend.",
      "Great for wallet balance and confirmation UX.",
    ],
    buildUseCase: "Bitcoin Infrastructure",
    category: "APIs",
    tags: ["Bitcoin", "API", "Explorer", "Open Source"],
    openSource: true,
    difficulty: "Intermediate",
    website: "https://blockstream.info",
    docs: "https://github.com/Blockstream/esplora/blob/master/API.md",
    github: "https://github.com/Blockstream/esplora",
    logo: "ES",
    featured: false,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Bitcoin roadmap", href: "/roadmaps/bitcoin" },
    ],
    projectIdeas: [
      {
        title: "Self Custody Tool",
        description: "Fetch address and transaction history with Esplora.",
        href: "/projects",
      },
    ],
  },
  {
    id: "nostr",
    slug: "nostr",
    name: "Nostr",
    description:
      "Decentralized protocol for notes, identity, and social apps.",
    overview:
      "Nostr is a simple, open protocol for decentralized social networking and signed events. Relays store messages; clients are interchangeable — a major freedom-tech surface for builders.",
    whyUse: [
      "Simple cryptographic identity model.",
      "Relay-based architecture that is easy to experiment with.",
      "Growing Lightning zap ecosystem.",
    ],
    buildUseCase: "Nostr Clients",
    category: "Protocols",
    tags: ["Nostr", "Social", "Identity", "Relays"],
    openSource: true,
    difficulty: "Intermediate",
    website: "https://nostr.com",
    docs: "https://github.com/nostr-protocol/nostr",
    github: "https://github.com/nostr-protocol/nostr",
    logo: "NO",
    featured: true,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Bitcoin roadmap", href: "/roadmaps/bitcoin" },
    ],
    projectIdeas: [
      {
        title: "Nostr Client",
        description: "Build a minimal client that reads and publishes notes.",
        href: "/projects",
      },
      {
        title: "Lightning Wallet",
        description: "Add zap-style Lightning tips to Nostr notes.",
        href: "/projects",
      },
    ],
  },
  {
    id: "spark",
    slug: "spark",
    name: "Spark",
    description:
      "Bitcoin statechain / Lightning-adjacent toolkit for fast transfers.",
    overview:
      "Spark is an emerging Bitcoin scaling approach focused on fast off-chain transfers with Bitcoin-backed state. It is useful to track as builders explore L2 and statechain designs.",
    whyUse: [
      "Explore newer Bitcoin transfer designs.",
      "Complement Lightning learning with adjacent L2 ideas.",
      "Early ecosystem — good for research-minded builders.",
    ],
    buildUseCase: "Bitcoin Infrastructure",
    category: "Protocols",
    tags: ["Bitcoin", "L2", "Statechains", "Payments"],
    openSource: true,
    difficulty: "Advanced",
    website: "https://www.spark.money",
    docs: "https://docs.spark.money",
    logo: "SP",
    featured: false,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Bitcoin roadmap", href: "/roadmaps/bitcoin" },
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
    ],
    projectIdeas: [
      {
        title: "Self Custody Tool",
        description: "Prototype fast transfer UX alongside on-chain flows.",
      },
    ],
  },
  {
    id: "zeus",
    slug: "zeus",
    name: "Zeus",
    description:
      "Mobile Lightning and Bitcoin wallet for power users and node runners.",
    overview:
      "Zeus is a mobile Bitcoin and Lightning wallet that connects to your own node or LSP. It is widely used by Lightning operators and a common reference for self-custody UX.",
    whyUse: [
      "Self-custody Lightning on mobile.",
      "Node-connected workflows for operators.",
      "Open-source wallet to study and contribute to.",
    ],
    buildUseCase: "Lightning Wallets",
    category: "Wallets",
    tags: ["Lightning", "Mobile", "Self-custody", "Wallet"],
    openSource: true,
    difficulty: "Intermediate",
    website: "https://zeusln.com",
    docs: "https://docs.zeusln.app",
    github: "https://github.com/ZeusLN/zeus",
    logo: "ZE",
    featured: false,
    sponsored: false,
    featuredPartner: false,
    clicks: 0,
    websiteClicks: 0,
    docsClicks: 0,
    learningPaths: [
      { title: "Lightning roadmap", href: "/roadmaps/lightning" },
    ],
    projectIdeas: [
      {
        title: "Self Custody Tool",
        description: "Study Zeus UX patterns for your own wallet project.",
        href: "/projects",
      },
    ],
  },
];
